### ISSUE TITLE
extension is not compatible with vscode version 1.70.0

### ISSUE THREAD

**Issue by huaxk** [asdine/vscode-cue#2]
When I install this extension, vscode popup notice:

`Can't install 'asdine.cue' extension because it is not compatible with the current version of Visual Studio Code (version 1.70.0).`

**Comment by asdine** [comment]
I have started building this extension on VS Code 1.71, so it's compatible from that version onwards.
Your VS Code version seems to not have been updated since [July 2022](https://code.visualstudio.com/updates/v1_70).
The fastest solution is to upgrade your VS Code version to the latest version.

**Comment by asdine** [comment]
Closing this, please reopen if the problem persists after the update.

**Comment by huaxk** [comment]
Thank you, solve problems after upgrading.
